# Generated by Django 3.0.3 on 2020-04-01 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='', max_length=12)),
                ('classes', models.TextField(default='', max_length=120)),
                ('subjects', models.CharField(choices=[('science', 'science'), ('math', 'math'), ('english', 'english')], default='', max_length=120)),
                ('pay', models.CharField(default='', max_length=12)),
                ('payment_method', models.CharField(choices=[('venmo', 'venmo'), ('cash', 'cash'), ('paypal', 'paypal')], default='', max_length=120)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('status', models.BooleanField(default=False))
            ],
        ),
    ]
