# Generated by Django 3.0.3 on 2020-02-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TutorSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default=0, max_length=12)),
                ('classes', models.TextField(default=0, max_length=120)),
                ('subjects', models.TextField(default=0, max_length=120)),
                ('pay', models.CharField(default=0, max_length=12)),
                ('payment_method', models.TextField(default=0, max_length=120)),
            ],
        ),
    ]
