# Generated by Django 3.0.3 on 2020-04-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsignup',
            name='num_rates',
            field=models.IntegerField(default=0),
        ),
    ]
