# Generated by Django 3.0.3 on 2020-03-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsignup',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
