# Generated by Django 3.0.2 on 2020-02-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorsignup',
            name='classes',
            field=models.TextField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='tutorsignup',
            name='pay',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='tutorsignup',
            name='payment_method',
            field=models.CharField(choices=[('venmo', 'venmo'), ('cash', 'cash'), ('paypal', 'paypal')], default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='tutorsignup',
            name='phone_number',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='tutorsignup',
            name='subjects',
            field=models.CharField(choices=[('science', 'science'), ('math', 'math'), ('english', 'english')], default='', max_length=120),
        ),
    ]
