# Generated by Django 3.0.3 on 2020-04-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorsignup',
            name='subjects',
            field=models.CharField(choices=[('english', 'english'), ('engineering', 'engineering'), ('humanities', 'humanities'), ('language', 'language'), ('math', 'math'), ('social sciences', 'social sciences'), ('sciences', 'sciences'), ('other', 'other')], default='', max_length=120),
        ),
    ]
