# Generated by Django 3.0.3 on 2020-04-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_tutorsignup_num_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsignup',
            name='name',
            field=models.TextField(default='', max_length=120),
        ),
    ]
