# Generated by Django 3.0.2 on 2020-02-24 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_auto_20200219_2238'),
        ('tutors', '0002_auto_20200219_2243'),
    ]

    operations = [
    ]
