# Generated by Django 3.0.3 on 2020-04-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_tutorsignup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorsignup',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
