# Generated by Django 3.0.2 on 2020-03-02 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_merge_20200224_1634'),
        ('tutors', '0003_merge_20200224_1635'),
    ]

    operations = [
    ]
