# Generated by Django 3.0.2 on 2020-03-02 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_merge_20200301_2114'),
        ('tutors', '0002_auto_20200223_1757'),
    ]

    operations = [
    ]
