# Generated by Django 3.0.3 on 2020-04-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsignup',
            name='name',
            field=models.TextField(default='', max_length=120),
        ),
    ]
