# Generated by Django 3.0.2 on 2020-02-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200216_1119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentSignupForm',
            new_name='StudentSignup',
        ),
    ]
