# Generated by Django 3.0.2 on 2020-02-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200216_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsignup',
            name='classes',
            field=models.TextField(default=0, max_length=120),
        ),
        migrations.AddField(
            model_name='studentsignup',
            name='phone_number',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
